import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/ThemeProvider';
import { geistMono, geistSans } from '@/lib/font';
import AppContext from './app-context';
import { Toaster } from '@/components/ui/sonner';
import UserProvider from '@/provider/user';
import accountApi from '@/api/account';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default async function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = await accountApi.profile();
    return (
        <UserProvider init={user}>
            <AppContext>
                <html lang='en' suppressHydrationWarning>
                    <body className={`${geistSans.variable} ${geistMono.variable}`}>
                        <ThemeProvider attribute='class' defaultTheme='light'>
                            {children}
                            <Toaster />
                        </ThemeProvider>
                    </body>
                </html>
            </AppContext>
        </UserProvider>
    );
}
