import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/ThemeProvider';
import { geistMono, geistSans } from '@/lib/font';
import AppContext from './app-context';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <AppContext>
            <html lang='en' suppressHydrationWarning>
                <body className={`${geistSans.variable} ${geistMono.variable}`}>
                    <ThemeProvider attribute='class' defaultTheme='light'>
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </AppContext>
    );
}
